---
- name: Deploy datadog agent with Ansible
  hosts: datadog-hosts
  become: "yes"
  roles:
    - { role: Datadog.datadog, become: "yes" }

  vars_files:
    - secrets.yml
  vars:
    service: emg
    datadog_api_key: "{{ datadog_api_key }}"
    datadog_config:
      tags:
        - "env:quiubas-dev"
        - "server_type:cloud"
        - "service_name:EMG"
        - "team:quiubas"
        - "environment:dev"
      log_level: INFO
      process_config:
        enabled: "true"
      apm_config:
        enabled: "true"
      logs_enabled: true
    network_config:
      enabled: true
    datadog_checks:
      emg:
        init_config:
        instances:
          logs:
            - type: file
              path: "/home/ec2-user/mylogs/*"
              service: "emg_service"
              source: "aws"